GrandTheftInfo/Controllers/EasterEggController.cs
using GrandTheftInfo.Core.Contracts;
using GrandTheftInfo.Core.Models.EasterEgg;
using GrandTheftInfo.Models;
using static GrandTheftInfo.Core.Constants.CustomErrorConstants;
using Microsoft.AspNetCore.Mvc;

namespace GrandTheftInfo.Controllers
{
    public class EasterEggController : BaseController
    {
        private readonly IEasterEggService _easterEggService;

        public EasterEggController(IEasterEggService easterEggService, IGameService gameService)
            : base(gameService)
        {
            _easterEggService = easterEggService;
        }

        public async Task<IActionResult> Index()
        {
            var easterEggs = await _easterEggService.AllAsync();
            var games = await GetAllGamesInfo();

            if (games == null || !games.Any())
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GamesNotFound
                });
            }

            var model = easterEggs.GroupBy(x => x.GameId).OrderByDescending(g => g.First().GameName);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add(int gameId)
        {
            var model = new EasterEggFormModel()
            {
                GameId = gameId,
                Games = await GetAllGamesInfo()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(EasterEggFormModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Games = await GetAllGamesInfo();
                return View(model);
            }

            try
            {
                await _easterEggService.AddAsync(model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var easterEgg = await _easterEggService.GetFormModelByIdAsync(id);

            if (easterEgg == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = EasterEggNotFound
                });
            }

            var editModel = new EasterEggFormModel()
            {
                Name = easterEgg.Name,
                Description = easterEgg.Description,
                ImageUrlOne = easterEgg.ImageUrlOne,
                ImageUrlTwo = easterEgg.ImageUrlTwo,
                GameId = easterEgg.GameId,
                Games = await GetAllGamesInfo()
            };

            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EasterEggFormModel model)
        {
            var easterEgg = await _easterEggService.GetFormModelByIdAsync(id);

            if (easterEgg == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = EasterEggNotFound
                });
            }

            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                await _easterEggService.EditAsync(id, model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var easterEgg = await _easterEggService.GetFormModelByIdAsync(id);

            if (easterEgg == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = EasterEggNotFound
                });
            }

            try
            {
                await _easterEggService.DeleteAsync(id);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GrandTheftInfo/Views/EasterEgg/Add.cshtml
@model EasterEggFormModel

@{
    ViewData["Title"] = "Add Easter Egg";
}

<div class="container">
    <h1 class="mt-4">Add Easter Egg</h1>

    <form method="post" asp-controller="EasterEgg" asp-action="Add">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" type="text" class="form-control" placeholder="Shoot the moon" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" type="text" class="form-control" ></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrlOne"></label>
                    <input asp-for="ImageUrlOne" type="text" class="form-control" />
                    <span asp-validation-for="ImageUrlOne" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrlTwo"></label>
                    <input asp-for="ImageUrlTwo" type="text" class="form-control" />
                    <span asp-validation-for="ImageUrlTwo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GameId"></label>
                    <select asp-for="GameId" class="form-control">
                        @foreach (var game in Model.Games)
                        {
                            <option value="@game.Id">@game.Name</option>
                        }
                    </select>
                </div>
            </div>
        </div>
        <div class="form-buttons mt-3">
            <input type="submit" value="Add" class="btn btn-outline-success" />
            <a asp-controller="EasterEgg" asp-action="Index" class="btn btn-outline-danger">Back</a>
        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GrandTheftInfo/Views/EasterEgg/Edit.cshtml
@model EasterEggFormModel

@{
    ViewData["Title"] = "Edit Easter Egg";
}

<div class="container">
    <h1 class="mt-4">Edit Easter Egg</h1>

    <form method="post" asp-controller="EasterEgg" asp-action="Edit">
        <div class="row">
            <div class="col">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" value="@Model.Name" type="text" class="form-control" placeholder="Shoot the moon" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrlOne"></label>
                    <input asp-for="ImageUrlOne" value="@Model.ImageUrlOne" type="text" class="form-control" />
                    <span asp-validation-for="ImageUrlOne" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrlTwo"></label>
                    <input asp-for="ImageUrlTwo" value="@Model.ImageUrlTwo" type="text" class="form-control" />
                    <span asp-validation-for="ImageUrlTwo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="GameId"></label>
                    <select asp-for="GameId" class="form-control">
                        @foreach (var game in Model.Games)
                        {
                            <option value="@game.Id">@game.Name</option>
                        }
                    </select>
                </div>
            </div>
        </div>
        <div class="form-buttons mt-3">
            <input type="submit" value="Edit" class="btn btn-outline-success" />
            <a asp-controller="EasterEgg" asp-action="Index" class="btn btn-outline-danger">Back</a>
        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GrandTheftInfo/Views/EasterEgg/Index.cshtml
@model IOrderedEnumerable<IGrouping<int,EasterEggViewModel>>

@{
    ViewData["Title"] = "Easter Eggs";
    var easterEggsCount = Model.Count();
    var firstItem = Model.Any() ? Model.First().Key : 0;
}

<div class="container">
    @if (easterEggsCount > 0)
    {
        @await Html.PartialAsync("_GameNavigationPartial", Model)
    }

    @foreach (var eggGroup in Model)
    {
        @foreach (var egg in eggGroup)
        {
            <div class="row egg-container" data-game-id="@eggGroup.Key">
                <div class="card mb-5">
                    <div class="card-content">
                        <div class="card-images p-3">
                            @if (string.IsNullOrEmpty(egg.ImageUrlTwo))
                            {
                                <a href="@egg.ImageUrlOne" target="_blank">
                                    <img class="card-img single-image" src="@egg.ImageUrlOne" alt="Card image cap">
                                </a>
                            }
                            else
                            {
                                <a href="@egg.ImageUrlOne" target="_blank">
                                    <img class="card-img double-image" src="@egg.ImageUrlOne" alt="Card image cap">
                                </a>
                                <a href="@egg.ImageUrlTwo" target="_blank">
                                    <img class="card-img double-image" src="@egg.ImageUrlTwo" alt="Card image cap">
                                </a>
                            }
                        </div>
                        <div class="card-body">
                            <h4>@egg.Name</h4>
                            <h6 class="mb-2 text-muted">@egg.GameName</h6>
                            <p>@egg.Description</p>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                            {
                                <span class="card-buttons">
                                    <a asp-controller="EasterEgg" asp-action="Edit" asp-route-id="@egg.Id" class="btn btn-outline-warning">Edit</a>
                                    <form method="post" asp-controller="EasterEgg" asp-action="Delete" asp-route-id="@egg.Id">
                                        <input type="submit" value="Delete" class="btn btn-outline-danger">
                                    </form>
                                </span>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    }

    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
    {
        <div class="card-button-new">
            <a id="addEggButton" href="@Url.Action("Add", "EasterEgg")" class="btn btn-outline-success">Add New Easter Egg</a>
        </div>
    }
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var radioButtons = document.querySelectorAll('.btn-check');
        var addEggButton = document.getElementById('addEggButton');

        if (@easterEggsCount > 0) {
            // Show all Easter eggs for the first game when the page is loaded
            var firstGameId = @firstItem;
            var firstEggContainer = document.querySelectorAll('.egg-container[data-game-id="' + firstGameId + '"]');
            firstEggContainer.forEach(function (egg) {
                egg.style.display = 'block';
            });

            if (addEggButton) {
                addEggButton.href += '?gameId=' + firstGameId;
            }
        }

        radioButtons.forEach(function (radio) {
            radio.addEventListener('change', function () {
                var gameId = this.getAttribute('data-game-id');
                var eggs = document.querySelectorAll('.egg-container');

                // Hide all Easter eggs
                eggs.forEach(function (egg) {
                    egg.style.display = 'none';
                });

                // Show Easter eggs for the selected game
                var selectedEggContainer = document.querySelectorAll('.egg-container[data-game-id="' + gameId + '"]');
                selectedEggContainer.forEach(function (egg) {
                    egg.style.display = 'block';
                });

                if (addEggButton) {
                    addEggButton.href = '@Url.Action("Add", "EasterEgg")' + '?gameId=' + gameId;
                }
            });
        });
    });
</script>

<style>
    .egg-container {
        display: none;
    }
    
    .card-content {
        display: flex;
        align-items: center; /* Optional: Align items vertically */
    }

    .card-images {
        flex: 0 0 auto; /* This ensures the width is determined by the content */
        margin-right: 10px; /* Optional: Adjust spacing between card-images and card-body */
    }

    .card-img {
        width: 100%; /* Ensure images fill the available width */
        height: auto; /* Maintain aspect ratio */
    }

    .single-image {
        max-width: 400px; /* Max width for a single image */
    }

    .double-image {
        max-width: 200px; /* Max width for each image when there are two images */
    }

    .card-buttons {
        float: right;
    }

</style>