GrandTheftInfo/Controllers/CheatController.cs
using GrandTheftInfo.Core.Contracts;
using GrandTheftInfo.Core.Models.Cheat;
using GrandTheftInfo.Models;
using static GrandTheftInfo.Core.Constants.CustomErrorConstants;
using Microsoft.AspNetCore.Mvc;

namespace GrandTheftInfo.Controllers
{
    public class CheatController : BaseController
    {
        private readonly ICheatService _cheatService;

        public CheatController(ICheatService cheatService, IGameService gameService) 
            : base(gameService)
        {
            _cheatService = cheatService;
        }

        public async Task<IActionResult> Index()
        {
            var cheats = await _cheatService.AllAsync();
            var games = await GetAllGamesInfo();

            if (games == null || !games.Any())
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GamesNotFound
                });
            }

            var model = cheats.GroupBy(x => x.GameId).OrderByDescending(g => g.First().GameName);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add(int gameId)
        {
            var model = new CheatFormModel
            {
                GameId = gameId,
                Games = await GetAllGamesInfo()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(CheatFormModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Games = await GetAllGamesInfo();
                return View(model);
            }

            try
            {
                await _cheatService.AddAsync(model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var cheat = await _cheatService.GetFormModelByIdAsync(id);

            if (cheat == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = CheatNotFound
                });
            }

            var editModel = new CheatFormModel()
            {
                Name = cheat.Name,
                CheatCode = cheat.CheatCode,
                Platform = cheat.Platform,
                GameId = cheat.GameId,
                Games = await GetAllGamesInfo(),
            };

            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CheatFormModel model)
        {
            var cheat = await _cheatService.GetFormModelByIdAsync(id);

            if (cheat == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = CheatNotFound
                });
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await _cheatService.EditAsync(id, model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var cheat = await _cheatService.GetFormModelByIdAsync(id);

            if (cheat == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = CheatNotFound
                });
            }

            try
            {
                await _cheatService.DeleteAsync(id);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GrandTheftInfo/Controllers/GameController.cs
using GrandTheftInfo.Core.Contracts;
using GrandTheftInfo.Core.Models.Game;
using GrandTheftInfo.Models;
using static GrandTheftInfo.Core.Constants.CustomErrorConstants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace GrandTheftInfo.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService _gameService;

        public GameController(IGameService gameService)
        {
            _gameService = gameService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var games = await _gameService.AllAsync();

            return View(games);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(GameFormModel model)
        {
            if (!ModelState.IsValid) 
            {
                return View(model);
            }

            try
            {
               await _gameService.AddAsync(model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var game = await _gameService.GetFormModelByIdAsync(id);

            if (game == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GameNotFound
                });
            }

            var editModel = new GameFormModel()
            {
                Name = game.Name,
                Description = game.Description,
                ImageUrl = game.ImageUrl,
                DatePublished = game.DatePublished
            };

            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, GameFormModel model)
        {
            var game = await _gameService.GetFormModelByIdAsync(id);

            if (game == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GameNotFound
                });
            }

            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                await _gameService.EditAsync(id, model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var game = await _gameService.GetFormModelByIdAsync(id);

            if (game == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GameNotFound
                });
            }

            try
            {
                await _gameService.DeleteAsync(id);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GrandTheftInfo/Controllers/MissionController.cs
using GrandTheftInfo.Core.Contracts;
using GrandTheftInfo.Core.Models.Mission;
using GrandTheftInfo.Models;
using static GrandTheftInfo.Core.Constants.CustomErrorConstants;
using Microsoft.AspNetCore.Mvc;

namespace GrandTheftInfo.Controllers
{
    public class MissionController : BaseController
    {
        private readonly IMissionService _missionService;

        public MissionController(IMissionService missionService, IGameService gameService)
            : base(gameService)
        {
            _missionService = missionService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var missions = await _missionService.AllAsync();
            var games = await GetAllGamesInfo();

            if (games == null || !games.Any())
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GamesNotFound
                });
            }

            var model = missions.GroupBy(x => x.GameId).OrderByDescending(g => g.First().GameName);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add(int gameId)
        {
            var model = new MissionFormModel
            {
                GameId = gameId,
                Games = await GetAllGamesInfo()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(MissionFormModel model)
        {
            if (!ModelState.IsValid) 
            {
                model.Games = await GetAllGamesInfo();
                return View(model);
            }

            try
            {
                await _missionService.AddAsync(model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var mission = await _missionService.GetFormModelByIdAsync(id);

            if (mission == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = MissionNotFound
                });
            }

            var editModel = new MissionFormModel()
            {
                Name = mission.Name,
                Description = mission.Description,
                PlaytroughUrl = mission.PlaytroughUrl,
                GameId = mission.GameId,
                Games = await GetAllGamesInfo(),
            };

            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, MissionFormModel model)
        {
            var mission = await _missionService.GetFormModelByIdAsync(id);

            if (mission == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = MissionNotFound
                });
            }

            if (!ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                await _missionService.EditAsync(id, model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var mission = await _missionService.GetFormModelByIdAsync(id);

            if (mission == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = MissionNotFound
                });
            }

            try
            {
                await _missionService.DeleteAsync(id);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GrandTheftInfo/Controllers/SongController.cs
using GrandTheftInfo.Core.Contracts;
using GrandTheftInfo.Core.Models.Song;
using GrandTheftInfo.Models;
using static GrandTheftInfo.Core.Constants.CustomErrorConstants;
using Microsoft.AspNetCore.Mvc;

namespace GrandTheftInfo.Controllers
{
    public class SongController : BaseController
    {
        private readonly ISongService _songService;

        public SongController(ISongService songService, IGameService gameService)
            : base(gameService)
        {
            _songService = songService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var songs = await _songService.AllAsync();
            var games = await GetAllGamesInfo();

            if (games == null || !games.Any())
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GamesNotFound
                });
            }

            var model = songs.GroupBy(x => x.GameId).OrderByDescending(g => g.First().GameName);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> AddSongWithRadio(int gameId)
        {
            var model = new SongFormModel()
            {
                GameId = gameId,
                Games = await GetAllGamesInfo(),
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add(string radioName)
        {
            var model = new SongFormModel()
            {
                Radio = radioName,
                RadioImageUrl = await _songService.GetRadioImageByName(radioName),
                Games = await GetAllGamesInfo(),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(SongFormModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await _songService.AddAsync(model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }


            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var song = await _songService.GetFormModelByIdAsync(id);

            if (song == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = SongNotFound
                });
            }

            var editModel = new SongFormModel()
            {
                Name = song.Name,
                VideoUrl = song.VideoUrl,
                Radio = song.Radio,
                RadioImageUrl = song.RadioImageUrl,
                GameId = song.GameId,
                Games = await GetAllGamesInfo()
            };

            return View(editModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SongFormModel model)
        {
            var song = await _songService.GetFormModelByIdAsync(id);

            if (song == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = SongNotFound
                });
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                await _songService.EditAsync(id, model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var song = await _songService.GetFormModelByIdAsync(id);

            if (song == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = SongNotFound
                });
            }

            try
            {
                await _songService.DeleteAsync(id);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GrandTheftInfo/Views/Shared/404CustomError.cshtml
@model CustomErrorViewModel

<div class="container text-center">
    <h1>404 Not Found</h1>
    <h2>@Model.Message</h2>
</div>

GrandTheftInfo/Views/Shared/500CustomError.cshtml
@model CustomErrorViewModel

<div class="container text-center">
    <h1>500 Bad Request</h1>
    <h2>@Model.Message</h2>
</div>

GrandTheftInfo/Views/Shared/_GameNavigationPartial.cshtml
@model IEnumerable<IGrouping<int, IGameServiceModel>>
@using GrandTheftInfo.Core.Contracts.ServiceModels

<div class="game-nav-container">
    <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
        @foreach (var group in Model)
        {
            var firstItem = group.First();
            <input type="radio" class="btn-check" name="btnradio" id="btnradio-@group.Key" data-game-id="@group.Key" autocomplete="off" @if (group.Key == Model.First().Key)
            {
                <text>checked</text>
            }/>
            <label class="btn btn-outline-primary" for="btnradio-@group.Key">@firstItem.GameName</label>
        }
    </div>
</div>

GrandTheftInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GrandTheftInfo</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/slate/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container-fluid p-0">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GrandTheftInfo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (this.User?.Identity?.IsAuthenticated ?? false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Game" asp-action="Index">Games</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Mission" asp-action="Index">Missions</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Cheat" asp-action="Index">Cheats</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="EasterEgg" asp-action="Index">Easter Eggs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="SaveGame" asp-action="Index">Save Games</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Song" asp-action="Index">Songs</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - GrandTheftInfo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>