GrandTheftInfo/Controllers/SaveGameController.cs
using GrandTheftInfo.Core.Contracts;
using GrandTheftInfo.Core.Models.SaveGame;
using GrandTheftInfo.Models;
using static GrandTheftInfo.Core.Constants.CustomErrorConstants;
using Microsoft.AspNetCore.Mvc;

namespace GrandTheftInfo.Controllers
{
    public class SaveGameController : BaseController
    {
        private readonly ISaveGameService _saveGameService;

        public SaveGameController(ISaveGameService saveGameService, IGameService gameService)
            :base(gameService)
        {
            _saveGameService = saveGameService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var allFiles = await _saveGameService.GetFilesAsync();
            var games = await GetAllGamesInfo();

            if (games == null || !games.Any())
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = GamesNotFound
                });
            }

            var model = allFiles.GroupBy(x => x.GameId).OrderByDescending(g => g.First().GameName);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add(int gameId)
        {
            var model = new SaveGameAddModel()
            {
                GameId = gameId,
                Games = await GetAllGamesInfo()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(SaveGameAddModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Games = await GetAllGamesInfo();
                return View(model);
            }

            if (await _saveGameService.FileExistsInCloud(model.File.FileName))
            {
                ViewBag.ErrorMessage = FilePresentInCloud;
                model.Games = await GetAllGamesInfo();
                return View(model);
            }

            try
            {
                await _saveGameService.UploadFileAsync(model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var saveGame = await _saveGameService.GetModelByIdAsync(id);

            if (saveGame == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = SaveGameNotFound
                });
            }

            var viewModel = new SaveGameEditModel()
            {
                FileName = saveGame.FileName,
                Description = saveGame.Description,
                GameId = saveGame.GameId,
                Games = await GetAllGamesInfo()
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, SaveGameEditModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Games = await GetAllGamesInfo();
                return View(model);
            }

            try
            {
                await _saveGameService.EditAsync(id, model);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var saveGame = await _saveGameService.GetModelByIdAsync(id);

            if (saveGame == null)
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = SaveGameNotFound
                });
            }

            if (!await _saveGameService.FileExistsInCloud(saveGame.FileName))
            {
                return View(NotFoundCustomError, new CustomErrorViewModel()
                {
                    Message = FileNotPresentInCloud
                });
            }

            try
            {
                await _saveGameService.DeleteAsync(id);
            }
            catch (Exception ex)
            {
                return View(BadRequestCustomError, new CustomErrorViewModel()
                {
                    Message = ex.Message
                });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

GrandTheftInfo/Views/SaveGame/Add.cshtml
@model SaveGameAddModel

@{
    ViewData["Title"] = "Add Save";
}

<div class="container">
    <h1 class="mt-4">Add Save</h1>

    @if (ViewBag.ErrorMessage != null)
    {
        <span class="text-danger">@ViewBag.ErrorMessage</span>
    }

    <form method="post" onsubmit="return preventDoubleSubmit(this);" asp-controller="SaveGame" asp-action="Add" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="GameId"></label>
            <select asp-for="GameId" class="form-control">
                @foreach (var game in Model.Games)
                {
                    <option value="@game.Id">@game.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <div class="form-group">
                <label asp-for="File"></label>
                <input asp-for="File" type="file" class="form-control">
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
        </div>
        <div class="form-buttons mt-3">
            <input type="submit" value="Add" class="btn btn-outline-success" />
            <a asp-controller="SaveGame" asp-action="Index" class="btn btn-outline-danger">Back</a>
        </div>
    </form>
</div>

<script>
    function preventDoubleSubmit(form) {
        if (form.getAttribute('data-submitted') === 'true') {
            return false;
        } else {
            form.setAttribute('data-submitted', 'true');
            return true;
        }
    }
</script>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GrandTheftInfo/Views/SaveGame/Edit.cshtml
@model SaveGameEditModel

@{
    ViewData["Title"] = "Edit Save";
}

<div class="container">
    <h1 class="mt-4">Edit Save</h1>

    <form method="post" asp-controller="SaveGame" asp-action="Edit" enctype="multipart/form-data">
        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="GameId"></label>
            <select asp-for="GameId" class="form-control">
                @foreach (var game in Model.Games)
                {
                    <option value="@game.Id">@game.Name</option>
                }
            </select>
        </div>
        <div class="form-group">
            <div class="form-group">
                <label asp-for="FileName"></label>
                <input asp-for="FileName" type="text" value="@Model.FileName" class="form-control" disabled>
                <span asp-validation-for="FileName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-buttons mt-3">
            <input type="submit" value="Edit" class="btn btn-outline-success" />
            <a asp-controller="SaveGame" asp-action="Index" class="btn btn-outline-danger">Back</a>
        </div>
    </form>
</div>  

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

GrandTheftInfo/Views/SaveGame/Index.cshtml
@model IOrderedEnumerable<IGrouping<int,SaveGameViewModel>>

@{
    ViewData["Title"] = "Save Games";
    var savesCount = Model.Count();
    var firstItem = Model.Any() ? Model.First().Key : 0;
}

<div class="container">
    @if (savesCount > 0)
    {
        @await Html.PartialAsync("_GameNavigationPartial", Model)
    }

    <div class="row">
        @foreach (var saveGameGroup in Model)
        {
            @foreach (var save in saveGameGroup)
            {
                <div class="col-sm-3 save-container" data-game-id="@saveGameGroup.Key">
                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">@save.FileName</h5>
                            <p class="card-text">@save.Description</p>
                            <p class="card-text">@save.GameName</p>
                            <a href="@save.BlobUri" class="btn btn-primary" download>Download</a>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                            {
                                <div class="card-buttons">
                                    <a asp-controller="SaveGame" asp-action="Edit" asp-route-id="@save.Id" class="btn btn-outline-warning">Edit</a>
                                    <form method="post" asp-controller="SaveGame" asp-action="Delete" asp-route-id="@save.Id">
                                        <input type="submit" value="Delete" class="btn btn-outline-danger">
                                    </form>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            }
        }
        @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
        {
        <div class="card-button-new">
            <a id="addSaveButton" href="@Url.Action("Add", "SaveGame")" class="btn btn-outline-success">Add New Save</a>
        </div>
        }
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var radioButtons = document.querySelectorAll('.btn-check');
        var addSaveButton = document.getElementById('addSaveButton');

        if(@savesCount > 0) {
            // Show all missions for the first game when the page is loaded
            var firstGameId = @firstItem;
            var firstSaveContainer = document.querySelectorAll('.save-container[data-game-id="' + firstGameId + '"]');
            firstSaveContainer.forEach(function (mission) {
                mission.style.display = 'block';
            });

            if (addSaveButton) {
                addSaveButton.href += '?gameId=' + firstGameId;
            }
        }

        radioButtons.forEach(function (radio) {
            radio.addEventListener('change', function () {
                var gameId = this.getAttribute('data-game-id');
                var saves = document.querySelectorAll('.save-container');

                // Hide all missions
                saves.forEach(function (save) {
                    save.style.display = 'none';
                });

                // Show missions for the selected game
                var selectedSaveContainer = document.querySelectorAll('.save-container[data-game-id="' + gameId + '"]');
                selectedSaveContainer.forEach(function (save) {
                    save.style.display = 'block';
                });
                
                if (addSaveButton) {
                    addSaveButton.href = '@Url.Action("Add", "SaveGame")' + '?gameId=' + gameId;
                }
            });
        });
    });
</script>

<style>
    .save-container {
        display: none;
    }

    .card-buttons {
        float: right;
    }
</style>